-- AlterTable
ALTER TABLE `RentHistory` ADD COLUMN `CUST_ID` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `RentHistory` ADD CONSTRAINT `RentHistory_CUST_ID_fkey` FOREIGN KEY (`CUST_ID`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
