-- AlterTable
ALTER TABLE `User` ADD COLUMN `CUST_ID` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_CUST_ID_fkey` FOREIGN KEY (`CUST_ID`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
